### ISSUE TITLE
Stubbing BraintreeRails::Persistence's #find then #new makes #new hang indefinitely

### ISSUE THREAD

**Issue by n0nick** [lyang/braintree-rails#24]
This was a very difficult and strange problem to track down.
I managed to create the following minimal test case:

```ruby
require 'active_model'
require 'braintree_rails/persistence'

class Bob
  include BraintreeRails::Persistence
end

describe 'the problem' do
  it 'stubs "new"' do
    allow(Bob).to receive(:new)
  end

  it 'stubs "find"' do
    allow(Bob).to receive(:find)
  end

  it 'gets stuck' do
    Bob.new
  end
end
```

When you run this test using
```sh
$ rspec a_spec.rb --order defined
```

The third `it` block simply gets stuck when running `Bob.new`. It seems that the stubbing (in this particular order) creates some infinite loop in [BraintreeRails::Persistence#find](https://github.com/lyang/braintree-rails/blob/master/lib/braintree_rails/persistence.rb#L12).

Adding the following lines to the `describe` block fixes the issue:
```ruby
  after :each do
    allow(Bob).to receive(:new).and_call_original
  end
```

This is as far as I got on my own :)
Let me know if you have any pointers, or if there's something else I can do.

**Comment by n0nick** [comment]
I can't reproduce this either now (RSpec 3.3.1, ruby 2.0.0-p594, OS X 10.10.4), so I'll close this.

Sorry it took me so long to response :) Thx!

**Comment by lyang** [comment]
Glad to hear it disappeared :)
