### ISSUE TITLE
Braintree::UnexpectedError (expected a gzipped response):

### ISSUE THREAD

**Issue by curbsaleem** [lyang/braintree-rails#27]
Hi
i am getting 'Braintree::UnexpectedError (expected a gzipped response)' 
while using following code
          Braintree::Transaction.sale(amount: amt, 
                                        merchant_account_id: ENV[merchant_id], 
                                        custom_fields: {user_id: user_id
                                                       },
                                        :credit_card => {
                                          :number => credit_card["number"],
                                          :expiration_month => credit_card["expiration_month"],
                                          :expiration_year => credit_card["expiration_year"],
                                          :cardholder_name => credit_card["cardholder_name"],
                                          :cvv => credit_card["cvv"]
                                        },
                                        :billing => {
                                          :country_code_alpha2 => "US"
                                        }
                                      )
Any idea how i can fix it?

**Comment by curbsaleem** [comment]
logs:

D, [2015-07-27T16:43:26.778537 #19617] DEBUG -- : [Braintree] [27/Jul/2015 11:13:26 UTC] POST /transactions
D, [2015-07-27T16:43:26.778982 #19617] DEBUG -- : [Braintree] <?xml version="1.0" encoding="UTF-8"?>
[Braintree] <transaction>
[Braintree]   <amount>2.98</amount>
[Braintree]   <merchant-account-id>f5zrp23rsjmmw6dg</merchant-account-id>
[Braintree]   <custom-fields>
[Braintree]     <user-id>555f176f69702d4812040000</user-id>
[Braintree]   </custom-fields>
[Braintree]   <credit-card>
[Braintree]     <number>424242******4242</number>
[Braintree]     <expiration-month>11</expiration-month>
[Braintree]     <expiration-year>2015</expiration-year>
[Braintree]     <cardholder-name>4242424242424242</cardholder-name>
[Braintree]     <cvv>***</cvv>
[Braintree]   </credit-card>
[Braintree]   <billing>
[Braintree]     <country-code-alpha2>US</country-code-alpha2>
[Braintree]   </billing>
[Braintree]   <type>sale</type>
[Braintree] </transaction>

I, [2015-07-27T16:43:27.119495 #19617]  INFO -- : [Braintree] [27/Jul/2015 11:13:27 UTC] POST /transactions 503
D, [2015-07-27T16:43:27.119849 #19617] DEBUG -- : [Braintree] [27/Jul/2015 11:13:27 UTC] 503 Service Unavailable

**Comment by lyang** [comment]
Hi @curbsaleem,
This seems like a server issue from the last two log lines:

    [2015-07-27T16:43:27.119495 #19617] INFO -- : [Braintree] [27/Jul/2015 11:13:27 UTC] POST /transactions 503
    [2015-07-27T16:43:27.119849 #19617] DEBUG -- : [Braintree] [27/Jul/2015 11:13:27 UTC] 503 Service Unavailable

Also matches Braintree's sandbox [status page event](https://status.braintreepayments.com/incidents/q9c6bgcyk4g6). Should be fixed now.
